imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

cocur_build:
    build_directory: %kernel.root_dir%/../gh-pages

braincrafted_bootstrap:
    css_preprocessor: sass
    fonts_dir: %kernel.root_dir%/../web/fonts/bootstrap
    icon_prefix: fa

# Assetic Configuration
assetic:
    filters:
        less:
            node:       /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to:   "\.less$"
        lessphp:
             file: %kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php
             apply_to: "\.less$"
        sass:
            bin: /usr/local/bin/sass
            apply_to: "\.scss$"
        cssrewrite: ~
    assets:
        documentation_css:
            inputs:
                - %kernel.root_dir%/../src/Braincrafted/Bundle/BootstrapDemoBundle/Resources/public/css/documentation.css
            filters:
                - cssrewrite
            output: css/documentation.css
        documentation_js:
            inputs:
                - %kernel.root_dir%/../src/Braincrafted/Bundle/BootstrapDemoBundle/Resources/public/js/documentation.js
            output: js/documentation.js
