imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trust_proxy_headers: false # Should Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - "BraincraftedBootstrapBundle:Form:form_div_layout.html.twig"

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    filters:
        less:
            node:       /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to:   "\.less$"
        cssrewrite: ~
    assets:
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/less/bootstrap.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/less/responsive.less
            output: bundles/braincraftedbootstrap/css/bootstrap.css
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-transition.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-alert.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-button.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-carousel.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-collapse.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-dropdown.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-modal.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-tooltip.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-popover.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-scrollspy.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-tab.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-typeahead.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/BootstrapBundle/Resources/bootstrap/js/bootstrap-affix.js
            output: bundles/braincraftedbootstrap/js/bootstrap.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

knp_menu:
   twig:
       template: "BraincraftedBootstrapBundle:Menu:menu.html.twig"
   templating: false
   default_renderer: twig

knp_paginator:
    template:
        pagination: BraincraftedBootstrapBundle:Pagination:pagination.html.twig
