imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

braincrafted_static_site:
    build_directory: %kernel.root_dir%/../gh-pages

braincrafted_bootstrap:
    less_filter: less
    customize_variables:
        variables_file: %kernel.root_dir%/Resources/less/variables.less
    auto_configure:
        assetic:       true # Automatically configure Assetic for BcBootstrap
        twig:          true # Automatically configure Twig for BcBootstrap
        knp_menu:      true # Automatically configure KnpMenuBundle for BcBootstrap
        knp_paginator: true # Automatically configure KnpPaginatorBundle for BcBootstap

# Assetic Configuration
assetic:
    filters:
        # lessphp:
        #     file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
        #     apply_to:   "\.less$"
        less:
            node:       /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to:   "\.less$"
        cssrewrite: ~
    assets:
        documentation_css:
            inputs:
                - %kernel.root_dir%/../src/Braincrafted/Bundle/BootstrapDemoBundle/Resources/public/css/documentation.css
            filters:
                - cssrewrite
            output: css/documentation.css
        documentation_js:
            inputs:
                - %kernel.root_dir%/../src/Braincrafted/Bundle/BootstrapDemoBundle/Resources/public/js/documentation.js
            output: js/documentation.js
